modLoader = "kotlinforforge"
loaderVersion = "[${versions.kotlin_forge},)"
license = "MIT"

[[mods]]
modId = "hexssence"
version = "${version}"
displayName = "Hexssence"
logoFile = "assets/hexssence/icon.png"
authors = "IllinaBurlace"
description = "Resource generation addon for Hex Casting"

[[dependencies.hexssence]]
modId = "forge"
mandatory = true
versionRange = "[${versions.forge_dependency},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexssence]]
modId = "minecraft"
mandatory = true
versionRange = "[${versions.minecraft},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexssence]]
modId = "architectury"
mandatory = true
versionRange = "[${versions.architectury},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexssence]]
modId = "cloth_config"
mandatory = true
versionRange = "[${versions.cloth_config},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexssence]]
modId = "hexcasting"
mandatory = true
versionRange = "[${versions.hexcasting},)"
ordering = "NONE"
side = "BOTH"
